services:
  database:
    container_name: movifier-db
    image: groonga/pgroonga:latest-alpine-16
    environment:
      POSTGRES_USER: movifier-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: movifier-db
    ports:
      - "5432:5432"
    volumes:
      - movifier-db-data:/var/lib/postgresql/data

  redis:
    container_name: movifier-redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - movifier-network

  imgpush:
    image: hauxir/imgpush:latest
    container_name: imgpush
    volumes:
      - data-images:/images
    networks:
      - movifier-network
    ports:
      - "5000:5000"
    environment:
      - MAX_UPLOADS_PER_MINUTE=100
      - MAX_UPLOADS_PER_HOUR=5000
      - MAX_UPLOADS_PER_DAY=100000
      - NAME_STRATEGY=uuidv4
#      - VALID_SIZES=[150,300,600,900,1200]

volumes:
  movifier-db-data:
  data-images:
networks:
  movifier-network:
    driver: bridge
